FROM ubuntu:22.04

# Install build dependencies
RUN apt-get update && \
    apt-get install -y gcc libzip-dev && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /build

# Copy source
COPY src/unzipper.c /build/

# Build
RUN gcc -o unzipper unzipper.c \
    -Wall -Wextra \
    -fstack-protector-all \
    -D_FORTIFY_SOURCE=2 \
    -lzip \
    -O2 && \
    strip --strip-all unzipper

CMD ["cat", "unzipper"]
